// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return web;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDEGtrnJAa127P7_DZVFV3rpfOtcTjfZE',
    appId: '1:342094745167:android:1b9834f18faa7577a0e43a',
    messagingSenderId: '342094745167',
    projectId: 'concept-2-a240c',
    storageBucket: 'concept-2-a240c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDEGtrnJAa127P7_DZVFV3rpfOtcTjfZE',
    appId: '1:342094745167:ios:1b9834f18faa7577a0e43a',
    messagingSenderId: '342094745167',
    projectId: 'concept-2-a240c',
    storageBucket: 'concept-2-a240c.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDEGtrnJAa127P7_DZVFV3rpfOtcTjfZE',
    appId: '1:342094745167:ios:1b9834f18faa7577a0e43a',
    messagingSenderId: '342094745167',
    projectId: 'concept-2-a240c',
    storageBucket: 'concept-2-a240c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDEGtrnJAa127P7_DZVFV3rpfOtcTjfZE',
    appId: '1:342094745167:windows:1b9834f18faa7577a0e43a',
    messagingSenderId: '342094745167',
    projectId: 'concept-2-a240c',
    storageBucket: 'concept-2-a240c.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDDEGtrnJAa127P7_DZVFV3rpfOtcTjfZE',
    appId: '1:342094745167:web:1b9834f18faa7577a0e43a',
    messagingSenderId: '342094745167',
    projectId: 'concept-2-a240c',
    storageBucket: 'concept-2-a240c.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDEGtrnJAa127P7_DZVFV3rpfOtcTjfZE',
    appId: '1:342094745167:web:1b9834f18faa7577a0e43a',
    messagingSenderId: '342094745167',
    projectId: 'concept-2-a240c',
    storageBucket: 'concept-2-a240c.firebasestorage.app',
  );
}
